import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[300px] h-screen bg-black fixed top-0 bottom-0 left-0"></div>
        <div className="bg-gradient-to-b from-zinc-950 to-red-900 w-[calc(100%-300px)] ml-[300px]">
          {children}
        </div>
      </body>
    </html>
  );
}
